buildscript {
    ext {
        compose_version = '1.6.7'
        room_version = '2.6.1'
        lifecycle_version = '2.8.2'
		kotlinVersion = "1.9.24"
    }
}

plugins {
    id("com.android.application") version "8.2.2" apply false
    id("org.jetbrains.kotlin.android") version "1.9.24" apply false
    id("org.jetbrains.kotlin.kapt") version "1.9.24" apply false
	id("com.google.dagger.hilt.android") version "2.51" apply false
}